version: '3.8'

services:
  backend:
    build: .
    ports:
      - "9000:9000"
    environment:
      - MONGO_URL=mongodb://db:27017/mydb
    depends_on:
      - db

  db:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
