openapi: 3.0.0
info:
  title: Truck Manager API
  version: "1.0.0"
  description: API documentation for the Truck Manager system

servers:
  - url: http://localhost:5000

paths:
  /admin/alldrivers:
    get:
      summary: Get all drivers
      tags:
        - Drivers
      responses:
        '200':
          description: A list of drivers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Driver'

  /admin/newdriver:
    post:
      summary: Create a new driver
      tags:
        - Drivers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewDriver'
      responses:
        '201':
          description: Driver created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  driver:
                    $ref: '#/components/schemas/Driver'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /admin/driver/{id}:
    get:
      summary: Get a driver by ID
      tags:
        - Drivers
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the driver
      responses:
        '200':
          description: Driver found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Driver'
        '404':
          description: Driver not found
        '500':
          description: Server error

    put:
      summary: Update a driver by ID
      tags:
        - Drivers
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewDriver'
      responses:
        '200':
          description: Driver updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Driver'
        '404':
          description: Driver not found
        '500':
          description: Server error

    delete:
      summary: Delete a driver by ID
      tags:
        - Drivers
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Driver deleted
        '404':
          description: Driver not found
        '500':
          description: Server error

components:
  schemas:
    Driver:
      type: object
      properties:
        _id:
          type: string
          example: "665a282c1cd34ddf8d984b6c"
        name:
          type: string
          example: Giannis
        lastname:
          type: string
          example: Papas
        licenseNumber:
          type: string
          example: "1347h743h71hf44j9f818fj3"

    NewDriver:
      type: object
      properties:
        name:
          type: string
          example: "Kostas"
        lastname:
          type: string
          example: "Papados"
        licenseNumber:
          type: string
          example: "AB123456"
