openapi: 3.0.0
info:
  title: Truck Manager API
  version: "1.0.0"
  description: API documentation for the Truck Manager system

servers:
  - url: http://localhost:5000

paths:
  /alldrivers:
    get:
      summary: Get all drivers
      responses:
        '200':
          description: A list of drivers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Driver'

  /newdriver:
    post:
      summary: Create a new driver
      tags:
        - Drivers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Kostas"
                lastname:
                  type: string
                  example: Papados
                licenseNumber:
                  type: string
                  example: "665a282c1cd34ddf8d984b6b"
      responses:
        '201':
          description: Driver created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Driver created successfully
                  Driver:
                    $ref: '#/components/schemas/Driver'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: server error

components:
  schemas:
    Driver:
      type: object
      properties:
        _id:
          type: string
          example: "665a282c1cd34ddf8d984b6c"
        name:
          type: string
          example: Giannis
        lastname:
          type: string
          example: Papas
        licenseNumber:
          type: string
          example: "1347h743h71hf44j9f818fj3"
