openapi: 3.0.0
info:
  title: Truck Manager API
  version: "1.0.0"
  description: API documentation for the Truck Manager system

servers:
  - url: http://localhost:${port}

paths:
  /alldrivers:
    get:
      summary: Get all drivers
      responses:
        '200':
          description: A list of drivers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Driver'

components:
  schemas:
    Driver:
      type: object
      properties:
        id:
          type: string
          example: "123"
        name:
          type: string
          example: "Driver 1"